### ISSUE TITLE
If Statement incorrent collapse

### ISSUE THREAD

**Issue by muk-as** [loganch/AutoIt-VSCode#107]
If ${1:<expression>} Then ${2:statement} in single string incorrect collapse
it will try find EndIf, but If in single string no have it

example - will collapse from If to Next
```
If @error Then Exit
For $i = 1 To 2
    $n=1
Next
```

**Comment by Danp2** [comment]
See [here](https://github.com/loganch/AutoIt-VSCode/issues/89#issuecomment-1152916111) where this issue is already documented.

**Comment by muk-as** [comment]
resolved by del 
`([iI]f\\b)` and `([eE]nd[iI]f)`
on https://github.com/loganch/AutoIt-VSCode/blob/master/syntaxes/autoit-language-configuration.json
If in one string now cant collapse
If in block still can collapse

**Comment by loganch** [comment]
@muk-as, it looks like the error isn't quite fixed, the `If` block doesn't actually fold properly, where the line including `EndIf` gets hidden as well.

I'm also going to mark this as duplicate since this is ongoing in issue #89  that @Danp2 linked to.
